### ISSUE TITLE
Deploying Tableau Noir with Traefik

### ISSUE THREAD

**Issue by jrenoux** [tableaunoir/tableaunoir#247]
Hi, 

I am currently trying to deploy tableau noir with Traefik, and while I manage to have buttons and the top bar appearing, I cannot draw or interact with it in any way. When I place my mouse in the zone where I'm supposed to draw, it disappears, but I can't draw. 
I do not see any error messages in traefik or docker logs. I am only using the frontend for now, as I don't need to share the boards. 
Here is my modified docker-compose file.
```
version: '3.8'                                                                                                                                                                                                                                                                                                                                                                                                                          
services:                                                                                                                                                                                                                                                                                                                                                                                                                               
  tableaunoir:                                                                                                                                                                                                                                                                                                                                                                                                                          
    container_name: tableaunoir                                                                                                                                                                                                                                                                                                                                                                                                         
    image: tableaunoir:latest                                                                                                                                                                                                                                                                                                                                                                                                           
    restart: unless-stopped                                                                                                                                                                                                                                                                                                                                                                                                             
    environment:                                                                                                                                                                                                                                                                                                                                                                                                                        
      - EXTERNAL_WS_URL="ws://tableaunoir.my-server.com:8181"                                                                                                                                                                                                                                                                                                                                                                           
      - EXTERNAL_HTTP_URL="http://tableaunoir.my-server.com:8182"                                                                                                                                                                                                                                                                                                                                                                       
    volumes:                                                                                                                                                                                                                                                                                                                                                                                                                            
      - /tableaunoir                                                                                                                                                                                                                                                                                                                                                                                                                    
    networks:                                                                                                                                                                                                                                                                                                                                                                                                                           
      - tableaunoir                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  frontend:                                                                                                                                                                                                                                                                                                                                                                                                                             
    container_name: frontend                                                                                                                                                                                                                                                                                                                                                                                                            
    image: nginx:1.19                                                                                                                                                                                                                                                                                                                                                                                                                   
    restart: unless-stopped                                                                                                                                                                                                                                                                                                                                                                                                             
    volumes_from:                                                                                                                                                                                                                                                                                                                                                                                                                       
      - tableaunoir:ro                                                                                                                                                                                                                                                                                                                                                                                                                  
    volumes:                                                                                                                                                                                                                                                                                                                                                                                                                            
      - ./docker/templates/frontend:/etc/nginx/templates:ro                                                                                                                                                                                                                                                                                                                                                                             
    ports:                                                                                                                                                                                                                                                                                                                                                                                                                              
      - 8182:80                                                                                                                                                                                                                                                                                                                                                                                                                         
    environment:                                                                                                                                                                                                                                                                                                                                                                                                                        
      - NGINX_HOST=tableaunoir.my-server.com
      - NGINX_PORT=80                                                                                                                                                                                                                                                                                                                                                                                                                   
    networks:                                                                                                                                                                                                                                                                                                                                                                                                                           
      - tableaunoir                                                                                                                                                                                                                                                                                                                                                                                                                     
      - traefik-proxy                                                                                                                                                                                                                                                                                                                                                                                                                   
    labels:                                                                                                                                                                                                                                                                                                                                                                                                                             
      - "traefik.enable=true"                                                                                                                                                                                                                                                                                                                                                                                                           
      - "traefik.docker.network=traefik-proxy"                                                                                                                                                                                                                                                                                                                                                                                          
      - "traefik.port=80"                                                                                                                                                                                                                                                                                                                                                                                                               
      # Entrypoint and TLS                                                                                                                                                                                                                                                                                                                                                                                                              
      - "traefik.http.routers.tableaunoir.entrypoints=https"                                                                                                                                                                                                                                                                                                                                                                            
      - "traefik.http.routers.tableaunoir.rule=Host(`tableaunoir.my-server.com`)"                                                                                                                                                                                              
      - "traefik.http.routers.tableaunoir.tls.certresolver=namecheap"                                                                                                                                                                                                                                                                                                                                                                   
      # Middlewares:                                                                                                                                                                                                                                                                                                                                                                                                                    
      - "traefik.http.routers.tableaunoir.middlewares=tableaunoir@docker"                                                                                                                                                                                                                                                                                                                                                               
      # Middleware cloud adds additional headers:                                                                                                                                                                                                                                                                                                                                                                                       
      - "traefik.http.middlewares.tableaunoir.headers.customFrameOptionsValue=SAMEORIGIN"                                                                                                                                                                                                                                                                                                                                               
      - "traefik.http.middlewares.tableaunoir.headers.framedeny=true"                                                                                                                                                                                                                                                                                                                                                                   
      - "traefik.http.middlewares.tableaunoir.headers.sslredirect=true"                                                                                                                                                                                                                                                                                                                                                                 
      - "traefik.http.middlewares.tableaunoir.headers.stsIncludeSubdomains=true"                                                                                                                                                                                                                                                                                                                                                        
      - "traefik.http.middlewares.tableaunoir.headers.stsPreload=true"                                                                                                                                                                                                                                                                                                                                                                  
networks:                                                                                                                                                                                                                                                                                                                                                                                                                               
    tableaunoir:                                                                                                                                                                                                                                                                                                                                                                                                                        
    traefik-proxy:                                                                                                                                                                                                                                                                                                                                                                                                                      
      external:                                                                                                                                                                                                                                                                                                                                                                                                                         
        name: traefik-proxy 
```

Do you see anything that could be the issue?
Thanks for the help.
