### ISSUE TITLE
Organisation of the repository (Typescript)

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#39]
The tool is now written in Typescript (in **src**). Javascript code (in **js**) is generated. The issue is that the repository contains both:
- the source code in TS
- the generated JS code so that https://tableaunoir.github.io/ works.

Do you know how to run the TS compiler during the github.io deployment phase of https://tableaunoir.github.io/?

**Comment by Naereen** [comment]
I think you should check-out GitHub actions, and especially https://github.com/marketplace/actions/typescript-compiler which appears to be able to compile code using typescript compiler.

**Comment by Vinetos** [comment]
For a school project, I used Github Action too compile the website and generate HTML/CSS/JS files and publish to the organisation website repository. 

I have opened #47

**Comment by francoisschwarzentruber** [comment]
The github action audeployment is still not running. The errors are:

```
Unexpected input(s) 'node-version', valid inputs are ['repository', 'ref', 'token', 'ssh-key', 'ssh-known-hosts', 'ssh-strict', 'persist-credentials', 'path', 'clean', 'fetch-depth', 'lfs', 'submodules']
The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128
```

Do not worry. For the deployment, I run a standard bash program on my computer.

**Comment by Vinetos** [comment]
For the unexpected input, here is a fixed version. The problem was that `uses: actions/setup-node@v1` was missing !
```
# This is a basic workflow to deploy the project to the website

name: Deploy to Github Pages

# Triggers the workflow on push or pull request but only for the master branch
on:
  push:
    branches: [ master ]
    tags:
      - v*

jobs:
  # Build the project
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
        
      - name: Build
        run: |
          npm clean-install
          npm run build
         
      # Deploy
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # Deployed to the organisation website
          REPOSITORY_NAME: tableaunoir/tableaunoir.github.io
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          # This is the folder the website is generated
          FOLDER: dist
          CLEAN: true
```
---
For the fail of the git process, according to the output of github actions :
```
/usr/bin/git commit -m Deploying to main from  @ 6da276ce06d82a2a118a42bff5d1dcb3f8fb7e69 🚀 --quiet --no-verify
/usr/bin/git push --force ***github.com/tableaunoir/tableaunoir.github.io.git github-pages-deploy-action/r2w5qhfur:main
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/tableaunoir/tableaunoir.github.io.git/'
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌
```
Probably because there is an error with the access token or its authorizations 
For instance, my access token has theses authorizations :
![image](https://user-images.githubusercontent.com/10145351/99889689-e888fa00-2c57-11eb-93f9-3375d79159aa.png)
